name: Generate pages

on:
  push:
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install deps
        run: npm i
      - name: Fetch latest database
        id: search-db
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const release = await github.request('GET /repos/{owner}/{repo}/releases/latest', {
              owner: 'tuat-static-syllabus',
              repo: 'tuat-static-syllabus'
            });
            for (const {name, browser_download_url} of release.data.assets) {
              if (name != "syllabus.sqlite"){
                continue;
              }
              return browser_download_url;
            }
            throw new Error("File not found!");
      - name: Download latest database
        run: wget "${{ steps.search-db.outputs.result }}" -O syllabus.sqlite
      - name: Generate files
        run: ./build_pages.sh
      - name: Push files to github.io
        run: |
          git clone https://lesmiscore:${{ secrets.GH_PAT }}@github.com/tuat-static-syllabus/tuat-static-syllabus.github.io GHP
          cd GHP
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          rm -rf generated/ || true
          cp -r ../generated/ .
          git add .
          git commit -am"automatic: push generated files @ $(date +'%Y%m%d')" || true
          GIT_EDITOR=true git merge origin/coding || git merge --abort
          git push
      - name: Compress generated files
        run: tar -cJf generated.tar.xz generated/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated.tar.xz
          path: generated.tar.xz
